### ISSUE TITLE
Resources prefixed by "kubernetes.io/" are explicitly filtered out of metrics

### ISSUE THREAD

**Issue by sblumenthal** [kubernetes/kube-state-metrics#2027] opened 2023-03-14 19:46 UTC
**What happened**:

Our infrastructure has multiple nodes defined with `kubernetes.io/network-bandwidth` as an allocatable resource type. However, these resources do not show up via `kube_node_status_allocatable`, `kube_node_status_capacity`, `kube_pod_container_resource_limits`, and `kube_pod_container_resource_requests`.

**What you expected to happen**:

I would expect metrics to be generated for these resource types.

**How to reproduce it (as minimally and precisely as possible)**:

1) Spin up a minikube cluster with the `metrics-server` addon enabled
2) Following [this doc](https://kubernetes.io/docs/tasks/administer-cluster/extended-resource-node/), add `kubernetes.io/network-bandwidth` as a resource to your node:
```
curl --header "Content-Type: application/json-patch+json" \
  --request PATCH \
  --data '[{"op": "add", "path": "/status/capacity/kubernetes.io~1network-bandwidth", "value": "1Mi"}]' \
  http://localhost:8001/api/v1/nodes/<node_name>/status
```
3) Following [this doc](https://kubernetes.io/docs/tasks/configure-pod-container/extended-resource/), add requests and limits to a container
4) Hit the metrics server and grep for `network`, no metrics regarding network bandwidth are generated

**Anything else we need to know?**:

I am not sure if this is a bug or a feature, it looks very explicit on the code side.

It looks both the [node store](https://github.com/kubernetes/kube-state-metrics/blob/999f97146e6103703c3dea8225458135bde229a6/internal/store/node.go#L337) and [pod store](https://github.com/kubernetes/kube-state-metrics/blob/999f97146e6103703c3dea8225458135bde229a6/internal/store/pod.go#L205) have support for extended resources, but that extended resource check checks whether the resource [is prefixed by](https://github.com/kubernetes/kube-state-metrics/blob/999f97146e6103703c3dea8225458135bde229a6/internal/store/utils.go#L172) `v1.ResourceDefaultNamespacePrefix`, which is [defined as](https://github.com/kubernetes/kubernetes/blob/1cb334960c4288fc7830a16c97f5f8489f140b5b/pkg/apis/core/types.go#L4733) `"kubernetes.io/"`

If this is intentional, then it would be great if there was a way to get resources that are prefixed by `"kubernetes.io/"`

**Environment**:
- kube-state-metrics version: 2.8.1
- Kubernetes version (use `kubectl version`): v1.26.1
- Cloud provider or hardware configuration: 
- Other info:

**Comment by mrueg** [comment] 2023-03-15 11:55
This might be a duplicate of https://github.com/kubernetes/kube-state-metrics/issues/1939

**Comment by sblumenthal** [comment] 2023-03-15 13:01
I think you are right, I had not found that issue, but it looks like the same problem to me

**Closed** 2023-03-15 13:03 UTC
Labels: kind/bug, needs-triage
