### ISSUE TITLE
Add metrics for tpr/crd objects

### ISSUE THREAD

**Issue by JosephSalisbury** [kubernetes/kube-state-metrics#303] opened 2017-11-13 17:11 UTC
I would find it useful to be able to have metrics for the number of tpr / crd objects currently in the cluster.

Happy to provide PRs if there's consensus on usefulness.

**Comment by brancz** [comment] 2017-11-13 18:01
Are you talking about CRD definitions or objects of that kind?

**Comment by JosephSalisbury** [comment] 2017-11-13 18:23
Yeah, to be specific, the number of objects of a specific CRD.

**Comment by tamalsaha** [comment] 2017-11-13 22:25
We are also interested in having state-metrics supporting CRDs created by third parties (example: https://github.com/appscode/voyager) . How does this project plan to support external CRDs? Adding them all in one project seems like a bad/unmaintainable idea.

**Comment by tamalsaha** [comment] 2017-11-13 22:40
@brancz , I was reading your blog post today https://brancz.com/2017/11/13/kube-state-metrics-the-past-the-present-and-the-future/ .Thanks for writing it, as it helped me understand the general architecture of this project.

May be this project can be structured in such a way that, third parties like us can write their own state-metrics server for CRDs or aggregate api servers. Then expose as a side-car /separate deployment that Prometheus scrapes. The issue is always the `client-go` package organization mess. But this can be made to work with some continued pain.

**Comment by brancz** [comment] 2017-11-14 08:17
@tamalsaha happy you liked the post. The way this should happen (and this is what the prometheus-operator and etcd-operator do), is that the controllers themselves should be the origin of this information. Actually we were hoping, that at some point, kube-state-metrics would not be necessary anymore, and instead the actual controllers of those objects expose these metrics.

**Comment by tamalsaha** [comment] 2017-11-14 08:23
> the controllers themselves should be the origin of this information. 

ah! I think we are on that path too. Our various operator currently expose prometheus metrics for GO process. We need to work on CRD specific metrics.

**Comment by JosephSalisbury** [comment] 2017-11-14 10:39
Operators exposing their own metrics for CRDs works for me.

**Comment by brancz** [comment] 2017-11-14 12:23
In that case I'll go ahead and close this :slightly_smiling_face: . Feel free to comment with follow up questions, should you have any.

**Closed by brancz** 2017-11-14 12:23 UTC

**Comment by fischerman** [comment] 2021-03-08 09:58
> The way this should happen (and this is what the prometheus-operator and etcd-operator do), is that the controllers themselves should be the origin of this information.

@brancz I just had a look at the Prometheus operator and I could only find metrics related to the operator but not individual custom resources. Were they removed at some point?
