### ISSUE TITLE
"Evicted" pods don't register metrics

### ISSUE THREAD

**Issue by yfried** [kubernetes/kube-state-metrics#1389] opened 2021-02-21 14:01 UTC
**What happened**:
I have many pods with Evicted state: 
```
kubectl get pod -A  | grep Evicted | wc -l
     117
```

But no metric with `reason=Evicted`. The following query returns empty for the last week
```
{job="kube-state-metrics", reason="Evicted"} == 1
```
**What you expected to happen**:
I expected the above query to return with metrics of the evicted pods.
**How to reproduce it (as minimally and precisely as possible)**:
Check that evicted nodes exist and then query prometheus as mentioned above

**Environment**:
- kube-state-metrics version: 1.9.7
- Kubernetes version (use `kubectl version`): 1.18
- Cloud provider or hardware configuration: EKS on AWS

**Comment by brancz** [comment] 2021-02-22 12:49
Which metric did you expect to be there but wasn't?

**Comment by yfried** [comment] 2021-02-24 11:52
> Which metric did you expect to be there but wasn't?

@brancz All `{job="kube-state-metrics", reason="Evicted"}` metrics are `0` even though there are eviction events

**Comment by csturgess93** [comment] 2021-03-17 10:59
Hi, I can confirm we are also experiencing the same issue. We have evicted pods in our cluster, but the query won't gather the metric. It works fine with `reason="Completed"` etc but `reason="Evicted"` unfortunately does not work.

**Comment by shabbir-taulia** [comment] 2021-03-18 20:39
can confirm this is happening in oiur cluster right now too
```
➜ (⎈ gke:test) tmp  ✗ k get po | grep -i evicted | wc -l
     996
```
But the metrics never show a value of `1` as far as we can look. Our current workaround is to use
```
kube_pod_status_phase{namespace="test",phase="Failed"}
```

**Comment by m1o1** [comment] 2021-04-08 14:40
Same, but we are using kube_pod_container_status_last_terminated_reason (issues#344), though since evicted pods seem to stick around and a new one is created, either one should work I guess.

We have some alerts, and `reason="OOMKilled"` works fine, but `reason="Evicted"` does not.

**Comment by CarpathianUA** [comment] 2021-04-14 19:12
Expiriencing the same!

**Comment by strangeman** [comment] 2021-05-05 06:10
We expiriencing the same problem

**Comment by ritheshgm** [comment] 2021-05-05 08:06
+1

**Comment by qingguee** [comment] 2021-05-19 07:35
+1 Looks like we also met this issue.

**Comment by yfried** [comment] 2021-05-23 06:34
Hi @brancz 
Looks like this is effecting many users.
Did you get a chance to look into this?

**Comment by saltbo** [comment] 2021-06-17 09:53
any progress on this issue?

**Comment by sedflix** [comment] 2021-06-23 06:07
+1

**Comment by cnelson** [comment] 2021-06-24 20:54
Same issue with `reason="Shutdown"` [which went beta in v1.21](https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/)

**Comment by slashpai** [comment] 2021-06-28 10:22
I tried `max_over_time`, `avg_over_time` and `sum_over_time` for `kube_pod_container_status_last_terminated_reason` all queries returned 0 even if `reason="Evicted` exists. So this value never seems to be incremented 

Example query
`max_over_time(kube_pod_container_status_last_terminated_reason{reason="Evicted"}[2h])`

I will try to figure out why Evicted reason is not registered in metric like other reasons

**Comment by fpetkovski** [comment] 2021-06-30 09:34
@yfried This is a bug with the version you are running where KSM conflates pod and container states. This should be fixed in versions 2.0.0 and later. The metric containing this information is `kube_pod_status_reason`

Since 1.x.x has other issues according to the [compatibility matrix](https://github.com/kubernetes/kube-state-metrics#compatibility-matrix), are you able to upgrade KSM to one of the 2.x.x versions? 

Also keep in mind that only pods can have the `Evicted` reason in their state. Metrics about pod _containers_ will likely not reflect this information.

**Comment by saltbo** [comment] 2021-06-30 11:30
> Note: The v2.0.0-alpha.2+ and master releases of kube-state-metrics work on Kubernetes v1.17 and v1.18 excluding Ingress or CertificateSigningRequest resource metrics. If you require those metrics and are on an older Kubernetes version, use v2.0.0-alpha.1 or v1.9.8 kube-state-metrics release.

Does v1.9.8 fix this problem? And can v1.9.8 be used on k8s v1.16?

**Comment by fpetkovski** [comment] 2021-06-30 11:36
Unfortunately v1.9.8 does not fix this problem, it's only fixed in 2.0.0 and onward

**Comment by saltbo** [comment] 2021-06-30 11:40
Yeah, we running v1.16, and no plan to update k8s version currently...

**Comment by fpetkovski** [comment] 2021-06-30 12:05
This is the commit which adds the `kube_pod_status_reason` metric that you are looking for: https://github.com/kubernetes/kube-state-metrics/commit/8f45cd8444ab206fe07f5af95095cd9015a1abd3#diff-9f1d27fdf1cb96ba2fc5bde3d90760eec19e66ee632a5756bf8da5ec28b54ab6.

We can try to backport parts of it to v1.9.8 but I am not sure what the current support policy is for pre 2.0.0 versions. Maybe @tariq1890 or @mrueg could provide their input before we raise the PR.

**Comment by mrueg** [comment] 2021-06-30 13:44
My personal thoughts here: I would still consider v1.9.x "community supported", which means no active feature development, backports etc. 
Backports for bug fixes can be contributed through the community and releases happen upon request.

**Comment by marcusio888** [comment] 2021-07-06 22:15
good night I could do it with the following metric
sum by (namespace) (kube_pod_status_reason {reason = "Evicted"})> 0
version 2.0.0 kube-state-metrics

**Comment by leepatrick-goop** [comment] 2021-07-08 19:43
+1

**Closed** 2021-12-05 21:28 UTC
Labels: kind/bug, lifecycle/rotten
