### ISSUE TITLE
kube_pod_container_info image incorrectly represents the actual image used

### ISSUE THREAD

**Issue by sebbonnet** [kubernetes/kube-state-metrics#1363] opened 2021-01-22 16:19 UTC
**What happened**:
`kube_pod_container_info` `image` label incorrectly represents the image the container is running on.

Given a 2 replicas deployment using `myregistry/test/my-image:v0.139.0` as the container image
`kube_pod_container_info` reports the wrong image for one of the pods
```
> kube_pod_container_info
kube_pod_container_info{pod="my-pod-c9b76bbbd-c8js9", image="myregistry/test/my-image:v0.139.0"} 
kube_pod_container_info{pod="my-pod-c9b76bbbd-trzrt", image="myregistry/test/my-image:v0.102.0"}
```

Using kubectl shows that the pod `.status.containerStatuses.image` has an image that is different than the one under `.spec.containers.image`.
This might be due to https://github.com/kubernetes/kubernetes/issues/74081
```
> kubectl get pods -o go-template="{{range .items}}{{.metadata.name}} spec: {{(index .spec.containers 0).image}} status: {{(index .status.containerStatuses 0).image}}\n{{end}}" | sed -e 's/\\n/\n/g' 
my-pod-c9b76bbbd-c8js9 spec: myregistry/test/my-image:v0.139.0 status: myregistry/test/my-image:v0.139.0
my-pod-c9b76bbbd-trzrt spec: myregistry/test/my-image:v0.139.0 status: myregistry/test/my-image:v0.102.0
``` 

**What you expected to happen**:
`kube_pod_container_info` should report the image under `.spec.containers.image`
Alternatively to avoid breaking backwark compatibility, a new `kube_pod_container_spec_info` could be created to pull the data from the spec.containers.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 1.6.0
- Kubernetes version (use `kubectl version`): 1.12

**Comment by dgrisonnet** [comment] 2021-01-22 18:08
> kube_pod_container_info should report the image under .spec.containers.image

I wouldn't agree with that, `kube_pod_container_info` is a metric that exposes various metadata about a running container. The latest observed metadata for containers can be found under `.status.containerStatuses`, whereas `.spec.containers` reflects the desired state in which we want the container to be. IMO, we are more interested in knowing what is actually running in the cluster rather than what is supposed to be running.

That being said, if there is really a bug with the content of `.status.containerStatuses.image`, I'd expect it be fixed in kubernetes directly instead of changing `kube_pod_container_info` data source.

**Comment by lilic** [comment] 2021-01-25 11:13
Thanks Damien!

@sebbonnet can you share your full output of get pods -oyaml where you think the problem is. So we can see the content of the other status fields. Thanks!

**Comment by sebbonnet** [comment] 2021-01-25 13:18
@dgrisonnet to be honest this was my initial reaction too, but I thought I'd raise this issue anyway to raise awareness and check if there is another way to solve this. Perhaps you have plans on exposing the container specs even though I can't really see what may be useful except from perhaps knowing which container have special securityContext requirements.

@lilic here is the yaml output for both pods - I had to strip out some details to make it possible to publish
Interestingly you can see that the `containerStatuses.imageID` in both cases is the same and corresponds to the image in the spec. Jumping on the nodes shows multiple tags for the pod that has the issue but only one image tag for the pod that has the correct image.
```
~# docker images | grep my-image
myregistry/test/my-image                                             v0.122.0                                             0d2594dbceef        6 months ago        391 MB
myregistry/test/my-image                                             v0.123.0                                             0d2594dbceef        6 months ago        391 MB
myregistry/test/my-image                                             v0.125.0                                             0d2594dbceef        6 months ago        391 MB
myregistry/test/my-image                                             v0.128.0                                             0d2594dbceef        6 months ago        391 MB
myregistry/test/my-image                                             v0.136.0                                             0d2594dbceef        6 months ago        391 MB
myregistry/test/my-image                                             v0.139.0                                             0d2594dbceef        6 months ago        391 MB

~$ sudo docker images | grep my-image
myregistry/test/my-image                                             v0.139.0                                             0d2594dbceef        6 months ago        391MB
```

_pod showing different image names under status_ 
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-25T10:46:45Z"
  labels:
    app: my-pod
    app.kubernetes.io/component: service
    app.kubernetes.io/managed-by: P2P
    app.kubernetes.io/version: v0.139.0
    pod-template-hash: 757b7b49f9
  name: my-pod-757b7b49f9-cc46g
  namespace: my-namespace
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: my-pod-757b7b49f9
    uid: 6d24c34c-5efa-11eb-b969-06fe60a61c48
  resourceVersion: "110489312"
  selfLink: /api/v1/namespaces/my-namespace/pods/my-pod-757b7b49f9-cc46g
  uid: 9e029f06-5efa-11eb-b969-06fe60a61c48
spec:
  containers:
  - env:
    - name: DEPLOYMENT_ENVIRONMENT
      value: my-namespace
    image: myregistry/test/my-image:v0.139.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: my-pod
    ports:
    - containerPort: 8080
      hostPort: 8080
      name: nginx-http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 12082
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 600Mi
      requests:
        cpu: 1500m
        memory: 600Mi
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_BIND_SERVICE
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: my-pod-token-ffxzx
      readOnly: true
  dnsPolicy: ClusterFirst
  hostNetwork: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: my-pod
  serviceAccountName: my-pod
  terminationGracePeriodSeconds: 60
  volumes:
  - name: my-pod-token-ffxzx
    secret:
      defaultMode: 420
      secretName: my-pod-token-ffxzx
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-01-25T10:46:45Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-25T10:47:07Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-25T10:47:07Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-01-25T10:46:45Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://c8a1ae06f61ea066badff7f6b5744c4d7929d90bc27f807d1a54028568e9207c
    image: myregistry/test/my-image:v0.122.0
    imageID: docker-pullable://myregistry/test/my-image@sha256:8d7eb654fc72c58a97455b77b308d6b18d8bda368844964b810e03ff6fe55ba1
    lastState: {}
    name: my-pod
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2021-01-25T10:46:47Z"
  phase: Running
  qosClass: Burstable
  startTime: "2021-01-25T10:46:45Z"
```

_pod showing the same image name under status_ 
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-25T10:47:48Z"
  labels:
    app: my-pod
    app.kubernetes.io/component: service
    app.kubernetes.io/managed-by: P2P
    app.kubernetes.io/version: v0.139.0
    pod-template-hash: 757b7b49f9
  name: my-pod-27wcf
  namespace: my-namespace
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: my-pod
    uid: 6d24c34c-5efa-11eb-b969-06fe60a61c48
  resourceVersion: "110489710"
  selfLink: /api/v1/namespaces/my-namespace/pods/my-pod-27wcf
  uid: c3f99ab9-5efa-11eb-b969-06fe60a61c48
spec:
  containers:
  - env:
    - name: DEPLOYMENT_ENVIRONMENT
      value: my-namespace
    image: myregistry/test/my-image:v0.139.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 8081
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    name: my-pod
    ports:
    - containerPort: 8080
      hostPort: 8080
      name: nginx-http
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 12082
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        memory: 600Mi
      requests:
        cpu: 1500m
        memory: 600Mi
  dnsPolicy: ClusterFirst
  hostNetwork: true
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: my-pod
  serviceAccountName: my-pod
  terminationGracePeriodSeconds: 60
  volumes:
  - name: my-pod-token-ffxzx
    secret:
      defaultMode: 420
      secretName: my-pod-token-ffxzx
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2021-01-25T10:47:48Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2021-01-25T10:49:20Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2021-01-25T10:49:20Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2021-01-25T10:47:48Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://a7eee92942013d03cdd4c7886c28a3e690c1cf355eba0782dee0fecdaa9a878a
    image: myregistry/test/my-image:v0.139.0
    imageID: docker-pullable://myregistry/test/my-image@sha256:8d7eb654fc72c58a97455b77b308d6b18d8bda368844964b810e03ff6fe55ba1
    lastState: {}
    name: my-pod
    ready: true
    restartCount: 0
    state:
      running:
        startedAt: "2021-01-25T10:48:58Z"
  phase: Running
  qosClass: Burstable
  startTime: "2021-01-25T10:47:48Z"
```

**Comment by codestalkerr** [comment] 2021-06-17 12:38
Is there any update to this issue as I am also facing the same problem! I have a dashboard that shows all the images used in different environments to keep track of and atm it doesn't show up right which makes it really hard for us.

**Closed** 2021-07-17 13:08 UTC
Labels: kind/bug, lifecycle/rotten

**Comment by Dutchy-** [comment] 2021-11-24 16:13
I have the exact same issue after updating a deployment:

Shortened for readability and confidentiality:

```
spec:
  containers:
  - image: <redacted>/aws-load-balancer-controller:v2.2.4-640709
status:
  containerStatuses:
  - image: <redacted>/aws-load-balancer-controller:v2.2.4
```

These are no longer in sync after updating the deployment. I would very much like to know if anybody found a solution.

**Comment by jianhaiqing** [comment] 2022-09-15 12:42
@Dutchy-  
I encounter the issue, too;
kubernetes version:  1.20.14 
containerd github.com/containerd/containerd v1.4.3 269548fa27e0089a8b8278fc4fc781d7f65a939b
The big discovery is that : these two images digest is the same. 

That is to say these two tags have no difference.
