### ISSUE TITLE
kube_daemonset_status_desired_number_scheduled is not updated when node is tainted

### ISSUE THREAD

**Issue by sylr** [kubernetes/kube-state-metrics#745] opened 2019-05-09 09:19 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The cluster autoscaler adds the ToBeDeletedByClusterAutoscaler taint on nodes it is about to delete.

It does not seem that the metric kube_daemonset_status_desired_number_scheduled is decreased if pods of the daemonset where scheduled on such nodes and do not tolerate this taint.

**What you expected to happen**:

If this taint appear the number of pods should be decreased if pods of the daemonset does not tolerate that taint.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.10.6
- Kube-state-metrics image version: v1.3.1

**Comment by brancz** [comment] 2019-05-10 18:22
Does the kubernetes API object update? kube-state-metrics is an exact mirror of what the API shows, and leaves interpretation up to the query.

**Comment by LiliC** [comment] 2019-06-27 15:38
@brancz @sylr I tested the above, and yes the metric is not updated because the API object itself is not updated. So the metric correctly reflects the state of the daemonset status. I guess this should be updated correctly in the status itself for the metric to reflect the change, kube-state-metrics is doing the correct thing here and this is not a bug and can be closed IMO.

**Comment by brancz** [comment] 2019-06-27 16:00
Thanks for double checking this @LiliC! I think in that case we can close this. @sylr feel free to re-open or create a new issue should there still be an issue when the object is actually updated.

**Closed by brancz** 2019-06-27 16:00 UTC
Labels: kind/bug
