### ISSUE TITLE
Metric kube_pod_container_status_terminated_reason don't detect all events

### ISSUE THREAD

**Issue by lombardialess** [kubernetes/kube-state-metrics#2153] opened 2023-08-18 12:43 UTC
**What happened**:
The metric kube_pod_container_status_terminated_reason is still experiment but since a very long time.
This metric can be very useful for monitoring alerts but is not detecting all "Errors" or "OOMKilled" often the event is not collected.

**What you expected to happen**:
Trace of any event of termination

**How to reproduce it (as minimally and precisely as possible)**:
I don't think is reproducible but for example OOMKilled is very often not detected in the metric

**Anything else we need to know?**:

**Environment**:
- kube-state-metrics version: 2.9.2
- Kubernetes version (use `kubectl version`): 1.25.6
- Cloud provider or hardware configuration: Azure AKS
- Other info:

**Comment by dashpole** [comment] 2023-08-24 16:42
cc @CatherineF-dev 
/triage accepted
/assign @dgrisonnet

**Comment by dobesv** [comment] 2023-08-30 00:12
Have you tried `kube_pod_container_status_last_terminated_reason` ?  It might be that the pod was restarted and the state was moved to the "last" field.

**Comment by TadeoCloud** [comment] 2023-09-11 11:33
Same problem here. When an OOMKill is detected, kube-metric always shows the value "1". But no more OOMKills have occurred.
![image](https://github.com/kubernetes/kube-state-metrics/assets/84514390/f18f853b-3a4c-4122-a006-9e4d62a775ed)

And if I test the function increase, it detects a change from null to zero.
![image](https://github.com/kubernetes/kube-state-metrics/assets/84514390/a3fff9e1-9709-4989-81e5-d7c2fcf925b2)

**Comment by TadeoCloud** [comment] 2023-09-11 11:43
When using kube-metrics v2.4.1 the sum value goes from "null" to "1" and then back to "null".
![image](https://github.com/kubernetes/kube-state-metrics/assets/84514390/03ce63c4-1805-43c8-b0aa-8036a3d025e4)

**Comment by dobesv** [comment] 2023-09-11 19:03
It would be nice to find a good alert query for this.

Maybe when querying the kube_pod_container_status_last_terminated_reason you also need to query whether the pod has restarted recently?

```
kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} and on(namespace, pod, container) (increase(kube_pod_container_status_restarts_total[30m]) > 0)
```

**Comment by TadeoCloud** [comment] 2023-09-12 08:24
> It would be nice to find a good alert query for this.
> 
> Maybe when querying the kube_pod_container_status_last_terminated_reason you also need to query whether the pod has restarted recently?
> 
> ```
> kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} and on(namespace, pod, container) (increase(kube_pod_container_status_restarts_total[30m]) > 0)
> ```

It seems to be working! I'm testing it. Thanks

**Comment by CatherineF-dev** [comment] 2023-10-11 01:44
QQ: is it working? 

If you don't have other questions, we will close it.

**Comment by TadeoCloud** [comment] 2023-10-11 07:17
Confirmed, it's working for me. Thanks!

**Comment by dgrisonnet** [comment] 2023-11-06 22:01
FWIW, there is also a new metrics in kubelet to better detect OOMKilled containers: https://github.com/kubernetes/kubernetes/pull/108004

Closing since the initial problem seem to have been resolved.

**Closed by dgrisonnet** 2023-11-06 22:01 UTC
Labels: kind/bug, triage/accepted
