### ISSUE TITLE
Failed to list *v1beta2.VerticalPodAutoscaler with  k8s v1.16

### ISSUE THREAD

**Issue by lihuixian001** [kubernetes/kube-state-metrics#1147] opened 2020-05-22 14:02 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:

the kube-state-metrics pod generates a lot of error logs:

E0522 13:57:29.070200       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1beta2.VerticalPodAutoscaler: the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
E0522 13:57:30.073936       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1beta2.VerticalPodAutoscaler: the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)
E0522 13:57:31.076380       1 reflector.go:156] pkg/mod/k8s.io/client-go@v0.0.0-20191109102209-3c0d1af94be5/tools/cache/reflector.go:108: Failed to list *v1beta2.VerticalPodAutoscaler: the server could not find the requested resource (get verticalpodautoscalers.autoscaling.k8s.io)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

helm upgrade --install kube-state-metrics stable/kube-state-metrics --version 2.8.5 -n monitor 

**Anything else we need to know?**:

**Environment**:
- Kubernetes version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.6-aliyun.1", GitCommit:"27fbcf7", GitTreeState:"", BuildDate:"2020-03-11T10:33:57Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}

- Kube-state-metrics image version
quay.io/coreos/kube-state-metrics v1.9.6

**Comment by tariq1890** [comment] 2020-05-24 05:25
Closing this as a duplicate of #1140 Please take a look at the solution posted there.

**Closed by tariq1890** 2020-05-24 05:25 UTC
