### ISSUE TITLE
Pod metrics reported for deleted pod

### ISSUE THREAD

**Issue by csmarchbanks** [kubernetes/kube-state-metrics#1157] opened 2020-06-12 20:03 UTC
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Running kube-state-metrics, and a different pod is deleted. After the other pod is removed kube-state-metrics continues to report metrics for that pod indefinitely.

**What you expected to happen**:
Metrics pertaining to a deleted pod to no longer be updated soon after deletion.

**How to reproduce it (as minimally and precisely as possible)**:
I don't know how to reproduce this deterministically. It has shown up in a couple environments, and restarting the kube-state-metrics pod will fix it.

It it is possibly related to kube-state-metrics startup. When we have seen this behavior usually the pod with metrics reported indefinitely was deleted shortly after the kube-state-metrics pod was started.

**Anything else we need to know?**:
I am running with auto-sharding turned on. I don't know if this is related or not.

**Environment**:
- Kubernetes version (use `kubectl version`): 1.14.10
- Kube-state-metrics image version: v1.9.5

**Comment by lilic** [comment] 2020-06-15 08:27
Have not seen this before, but that k8s version we don't support anymore in the ksm version you are running. https://github.com/kubernetes/kube-state-metrics#compatibility-matrix So curious if it has anything to do with that? Have you been able to reproduce this on later k8s versions as well so we can take that out of account? (don't think much changed in pod APIs since then, but still worth excluding)

**Comment by csmarchbanks** [comment] 2020-06-17 22:14
It does seem like the pod API shouldn't have changed much. I had been running without sharding on 1.9.5 for a couple months and did not notice this issue, so first I am trying to turn off sharding and see if the issue still occurs on the same version. If it does I will downgrade.

**Comment by csmarchbanks** [comment] 2020-07-06 17:58
Sorry about the slow updates, wanted to make sure we gave it enough time. Since turning off sharding we have not seen any issues with reporting metrics for deleted pods.

**Comment by brancz** [comment] 2020-07-08 08:43
I have a feeling that this is a dupe of https://github.com/kubernetes/kube-state-metrics/issues/694. I have some idea what might be wrong, but currently no time to look deeper into it.

**Closed** 2020-12-05 10:41 UTC
Labels: kind/bug, lifecycle/rotten
