### ISSUE TITLE
kube_pod_status_reason metric can't come on Prometheus

### ISSUE THREAD

**Issue by ebrudalkir** [kubernetes/kube-state-metrics#1158] opened 2020-06-18 08:38 UTC
I want to set alarm if pod's status evicted. But kube_pod_status_reason metric can't come on Prometheus. Just this metrics shown Evicted status. How can solve this problem?

kube_pod_status_reason 

pod=<pod-name>
namespace=<pod-namespace>
reason=<NodeLost|Evicted|UnexpectedAdmissionError>

**Comment by lilic** [comment] 2020-07-09 13:40
@ebrudalkir  Can you clarify what you are having problems with. Is it that you cannot see the kube_pod_status_reason label having Evicted status?

**Comment by nickytd** [comment] 2020-07-13 14:48
Same here. Just installed prometheus-operator 8.16.1 which requires kube-state-metrics-2.8.10 helm chart which brings kube-state-metrics:v1.9.7 with pod collector enabled. However upon scratching the endpoint not kube_pod_status_reason is present. Although there are pods in Evicted sates which should be noted by the metric above. K8S version is 1.17.7 in my case. And the same can be easily reproduced with minikube  setup and K8S v1.18.3 [minikube sample setup](https://github.com/nickytd/minikube-logging-monitoring)

**Comment by lilic** [comment] 2020-07-13 14:58
https://github.com/kubernetes/kube-state-metrics/pull/1013 This is because that metric is only present in master and will be added to the 2.0 kube-state-metric release. Closing this issue, as its normal for it to not be on 1.9.x release. If its not showing up in master kube-state-metrics version please reopen the issue, thanks!

**Closed by lilic** 2020-07-13 14:58 UTC

**Comment by nickytd** [comment] 2020-07-13 15:00
Thanks 👍
