### ISSUE TITLE
CronJob errors when running on 1.6.x without alpha features enabled

### ISSUE THREAD

**Issue by atombender** [kubernetes/kube-state-metrics#251] opened 2017-09-05 18:04 UTC
We're running on 1.6.7 on GKE, without alpha features enabled. This causes kube-state-metrics to fail with this error:

```
kube-state-metrics E0905 18:02:56.748146       1 reflector.go:201] k8s.io/kube-state-metrics/collectors/cronjob.go:86: Failed to list *v2alpha1.CronJob: the server could not find the requested resource
```

**Comment by matthiasr** [comment] 2017-09-05 18:07
Do the other metrics work & it's just a noisy log, or is this breaking it
completely?

**Comment by atombender** [comment] 2017-09-05 18:13
The other metrics work. It's just very noisy. It's emitted twice every second.

**Comment by zouyee** [comment] 2017-09-06 02:27
using `--collect` flag to enable metrics which you want

**Comment by brancz** [comment] 2017-09-06 07:54
Dupe of https://github.com/kubernetes/kube-state-metrics/issues/212. This is unfortunately not as easy of a problem to solve as kube-state-metrics is not versioned along with Kubernetes, so it's unclear which collectors would be in which stage. Therefore we default to enabling all, and users can enable only those collectors they care about.

**Comment by matthiasr** [comment] 2017-09-06 08:16
Ah great, that's the issue I wanted to look up! I think we can close this as a duplicate then?

**Closed** 2017-09-06 10:04 UTC
