### ISSUE TITLE
kube-state-metrics 2.9.2 is not generating custom metrics with namespace role

### ISSUE THREAD

**Issue by ukumar009** [kubernetes/kube-state-metrics#2098] opened 2023-06-16 22:53 UTC
**What happened**:

When using kube-state-metrics with custom config with namespace role. It worked well until 2.8.2 It started failing in 2.9.2 version. I see metrics not getting generated with an error 

```
1 reflector.go:140] pkg/mod/k8s.io/client-go@v0.26.5/tools/cache/reflector.go:169: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: customresourcedefinitions.apiextensions.k8s.io is forbidden: User "system:serviceaccount:namespace:role-name" cannot list resource "customresourcedefinitions" in API group "apiextensions.k8s.io" at the cluster scope
```

**What you expected to happen**:

Metrics should be displayed with namespace role. This CRDs are part of namespace. So, it should list those CRDs in the metrics with custom-config file.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy kube-state-metrics with namespace role. Pass any custom config to kube-state-metrics error can be seen in logs.

**Anything else we need to know?**:

N/A

**Environment**:
- kube-state-metrics version:  2.9.2
- Kubernetes version (use `kubectl version`): Can be reproduced on any version.
- Cloud provider or hardware configuration: N/A
- Other info: N/A

**Comment by rexagod** [comment] 2023-06-25 17:36
CRDs (`customresourcedefinitions.apiextensions.k8s.io`) are global resource and hence ideally require a service account to be binded to a cluster role to enable KSM to watch for all GVKs present under them. I'll document this more explicitly in the README.

Thanks for pointing it out.

**Comment by dgrisonnet** [comment] 2023-06-27 16:43
This is a duplicate of #2100, custom metrics now requires rbac permissions on the CRD resource. We will update the documentation soon, sorry for the inconvenience.

**Closed by dgrisonnet** 2023-06-27 16:43 UTC
Labels: kind/bug, needs-triage
